apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eclair.fullname" . }}-config
  labels:
    app: {{ template "eclair.name" . }}
    chart: {{ template "eclair.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
