apiVersion: v1
kind: Service
metadata:
  name: {{ template "eclair.fullname" . }}-internal
  labels:
    app: {{ template "eclair.name" . }}
    chart: {{ template "eclair.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.internalServices.rpcPort }}
      targetPort: rpc
  selector:
    app: {{ template "eclair.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eclair.fullname" . }}-external
  labels:
    app: {{ template "eclair.name" . }}
    chart: {{ template "eclair.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.externalServices.type }}
  ports:
    - name: p2p
      port: {{ .Values.externalServices.p2pPort }}
      targetPort: p2p
  selector:
    app: {{ template "eclair.name" . }}
    release: {{ .Release.Name }}
