apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lnd.fullname" . }}
  labels:
    app: {{ template "lnd.name" . }}
    chart: {{ template "lnd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "lnd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "lnd.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.configurationFile }}
      initContainers:
        - name: copy-lnd-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/lnd.conf /root/.lnd/lnd.conf']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /root/.lnd/
      {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ template "lnd.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["lnd"]
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.internalServices.rpcPort }}
            - name: rest
              containerPort: {{ .Values.internalServices.restPort }}
            - name: prometheus
              containerPort: {{ .Values.internalServices.prometheusPort }}
            - name: p2p
              containerPort: {{ .Values.externalServices.p2pPort }}
          volumeMounts:
            - name: data
              mountPath: /root/
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /root/.lnd/lnd.conf
              subPath: lnd.conf
            {{- end }}
            {{- if .Values.autoUnlock }}
            - name: secrets
              mountPath: /passwords/wallet_password
              subPath: wallet_password
            {{- end }}
          lifecycle:
            preStop:
              exec:
                # Make sure we safely quit lnd so we don't corrupt
                # anything
                command: ["/bin/lncli", "-n", "{{ .Values.network }}", "stop"]
        {{- if .Values.rtl.enable }}
        - name: rtl
          image: {{ .Values.rtl.image.repository }}:{{ .Values.rtl.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.rtl.port }}
          env:
            {{- range $key, $value := .Values.rtl.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /root/
          resources:
            requests:
              cpu: "10m"
        {{- end }}
        {{- if .Values.lndmon.enable }}
        - name: lndmon
          image: {{ .Values.lndmon.image.repository }}:{{ .Values.lndmon.image.tag }}
          args:
            - "--lnd.network={{ .Values.lndmon.lndNetwork }}" 
            - "--lnd.host={{ .Values.lndmon.lndHost }}" 
            - "--prometheus.listenaddr={{ .Values.lndmon.listenaddr }}" 
          ports:
            - name: lndmon
              containerPort: {{ .Values.lndmon.port }}
          volumeMounts:
            - name: data
              mountPath: /root/
          resources:
            requests:
              cpu: "10m"
        {{- end }}
      volumes:
        {{- if .Values.autoUnlock }}
        - name: secrets
          secret:
            secretName: {{ template "lnd.fullname" . }}
        {{- end }}
        {{- if .Values.configurationFile }}
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "lnd.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "lnd.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
