apiVersion: v1
appVersion: 0.10.2
description: A C implementation of a Lightning Network node
engine: gotpl
home: https://github.com/elementsproject/c-lightning
keywords:
- c-lightning
- cryptocurrency
- blockchain
- bitcoin
maintainers:
- email: kwinten@flitz.be
  name: kiwiidb
name: c-lightning
sources:
- https://github.com/kubernetes/charts
version: 0.3.2