# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: kiwiidb/c-lightning
  tag: v0.10.2
  pullPolicy: Always

# Ports that are exposed to other pods in your cluster
internalServices:
  rpcPort: 9737

# Ports that are visible outside your cluster
externalServices:
  p2pPort: 9735
  type: LoadBalancer

  # Ingress for Sparko REST API
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: cln.dev.flitz.be
      paths:
        - path: /
  tls:
    - hosts:
        - cln.dev.flitz.be
      secretName: cln-tls-secret

args:
  - "--disable-plugin=bcli" 
  - "--plugin=/opt/lightningd/plugins/trustedcoin_linux_amd64"
  - "--plugin=/opt/lightningd/plugins/sparko_linux_amd64"
  - "--plugin=/opt/lightningd/plugins/rebalance/rebalance.py"
  - "--plugin=/usr/local/bin/clboss"
  - "--sparko-host=0.0.0.0"
  - "--experimental-offers"
  # required when extra config enabled
  - "--conf=/root/config/lightning.conf"
boltz:
  api: https://boltz.exchange/api
  node: 026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2
extraConfig:
  enabled: false
  secretName: c-lightning-extra-config

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 300m
