# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lightninglabs/lnd
  tag: v0.14.1-beta
  pullPolicy: IfNotPresent

# Ports that are exposed to other pods in your cluster
internalServices:
  rpcPort: 10009
  restPort: 8080

# Ingress for REST API
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: lnd.dev.flitz.be
      paths:
        - path: /
  tls:
    - hosts:
        - lnd.dev.flitz.be
      secretName: lnd-tls-secret

# Ports that are visible outside your cluster
externalServices:
  p2pPort: 9735
  type: LoadBalancer

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 5Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

# The network lnd is running on
network: testnet
# network: mainnet

# Custom lnd configuration file used to override default lnd settings
configurationFile:
  lnd.conf: |-
    bitcoin.active=1
    bitcoin.mainnet=0
    bitcoin.testnet=1
    debuglevel=info
    bitcoin.node=neutrino
    neutrino.addpeer=faucet.lightning.community
    neutrino.addpeer=lnd.bitrefill.com:18333
    rpclisten=0.0.0.0:10009
    tlsextradomain=nodes-lnd-internal.nodes
    tlsextradomain=lnd.dev.flitz.be
    tlsextraip=0.0.0.0
    protocol.wumbo-channels=1
    wallet-unlock-password-file=/passwords/wallet_password
autoUnlock: true
autoUnlockPassword: password

lit:
  enable: false
  image:
    repository: lightninglabs/lightning-terminal
    tag: v0.6.0-alpha